export type Car = {
  id: string;
  vin: string;
  model_id: string;
  year?: number | null;
  fuel_type?: string | null;
  transmission?: string | null;
  seats?: number | null;
  licensePlate?: string | null;
  location_id?: string | null;
  engine_capacity?: number | null;
  status?: string | null;
  body_type?: string | null;
  drive_type?: string | null;
  color?: string | null;
  doors?: number | null;
  created_at: string;
  photos?: string[];
  content?: string;
  lat?: number;
  long?: number;
  address: string;
  pickupInfo: string;
  returnInfo: string;
  isDelivery: boolean;
  deliveryFee: number;
  includeMileage: number;
  price: number;
  deposit: number;
  currency?: string;
  openTime?: number;
  closeTime?: number;
  minRentPeriod?: number;
  maxRentPeriod?: number;
  intervalBetweenBookings?: number;
  ageRenters?: number;
  minDriverLicense?: number;
  isInstantBooking?: boolean;
  isSmoking?: boolean;
  isPets?: boolean;
  isAbroad?: boolean;
};
