export type Car = {
  id: string | undefined;
  vin: string;
  modelId: string;
  year?: number | null;
  fuelType?: string | null;
  transmission?: string | null;
  seats?: number | null;
  licensePlate?: string | null;
  locationId?: string | null;
  engineCapacity?: number | null;
  status?: string | null;
  bodyType?: string | null;
  driveType?: string | null;
  color?: string | null;
  doors?: number | null;
  photos?: string[];
  content?: string;
  lat?: number;
  long?: number;
  address: string;
  pickupInfo: string;
  returnInfo: string;
  isDelivery: boolean;
  deliveryFee: number;
  includeMileage: number;
  price: number;
  deposit: number;
  currency?: string;
  openTime?: number;
  closeTime?: number;
  minRentPeriod?: number;
  maxRentPeriod?: number;
  intervalBetweenBookings?: number;
  ageRenters?: number;
  minDriverLicense?: number;
  isInstantBooking?: boolean;
  isSmoking?: boolean;
  isPets?: boolean;
  isAbroad?: boolean;
};

export type CarUpdatePayload = Partial<Omit<Car, "id" | "created_at">>;
