export type Car = {
  models: any;
  id: string;
  vin: string;
  modelId: string;
  year?: number | null;
  fuelType?: string | null;
  transmission?: string | null;
  seats?: number | null;
  licensePlate?: string | null;
  locationId?: string | null;
  engineCapacity?: number | null;
  status?: string | null;
  bodyType?: string | null;
  driveType?: string | null;
  color?: string | null;
  doors?: number | null;
  photos?: string[] | null;
  content?: string | null;
  lat?: number | null;
  long?: number | null;
  address: string;
  pickupInfo: string;
  returnInfo: string;
  isDelivery: boolean;
  deliveryFee: number;
  includeMileage: number;
  price: number;
  deposit: number;
  currency?: string | null;
  openTime?: number | null;
  closeTime?: number | null;
  minRentPeriod?: number | null;
  maxRentPeriod?: number | null;
  intervalBetweenBookings?: number | null;
  ageRenters?: number | null;
  minDriverLicense?: number | null;
  isInstantBooking?: boolean | null;
  isSmoking?: boolean | null;
  isPets?: boolean | null;
  isAbroad?: boolean | null;
  owner?: string | null;
  ownerId?: string | null;
};
